
package pBase;

import java.util.LinkedList;
import javax.swing.JOptionPane;

public class SERVICIOS extends javax.swing.JDialog {
int total=0,E=0,SH=0,EXTR=0,NETO;
LinkedList<String> ll = new LinkedList<String>();
LinkedList<String> notas = new LinkedList<String>();
String recibo="";
int cubo[][] = new int[2][5];
int  L,HEx,EX,TAL,actual;
    public SERVICIOS(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NOTA = new javax.swing.JTextArea();
        add = new javax.swing.JButton();
        cantidad = new javax.swing.JSpinner();
        txtTotal = new javax.swing.JTextField();
        BF = new javax.swing.JRadioButton();
        Salir = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DI1 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        addL = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Salir1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Gym = new javax.swing.JRadioButton();
        Spa = new javax.swing.JRadioButton();
        Canchas = new javax.swing.JRadioButton();
        txtTotal1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        NOTA2 = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        extras = new javax.swing.JTextField();
        costo2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        add2 = new javax.swing.JButton();
        horas = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lavadora = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        Salir2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtTotal2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        CUENTA = new javax.swing.JTextArea();

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(450, 50));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel37.setText("$");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, -1, -1));

        NOTA.setBackground(new java.awt.Color(255, 204, 153));
        NOTA.setColumns(20);
        NOTA.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NOTA.setRows(5);
        NOTA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jScrollPane1.setViewportView(NOTA);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 340, 110));

        add.setBackground(new java.awt.Color(153, 255, 153));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel2.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 70, 30));

        cantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cantidad.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        cantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cantidadStateChanged(evt);
            }
        });
        jPanel2.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 90, 30));

        txtTotal.setBackground(new java.awt.Color(255, 255, 102));
        txtTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 51, 51)));
        jPanel2.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 150, 60));

        BF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BF.setText("Buffete  incluido");
        BF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFActionPerformed(evt);
            }
        });
        jPanel2.add(BF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aceptar.jpeg.png"))); // NOI18N
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
        });
        jPanel2.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 110, 90));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("No° Personas");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Aceptar/Salir");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 100, -1));

        DI1.setBackground(new java.awt.Color(255, 255, 255));
        DI1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DI1.setText("Desayuno incluido");
        DI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DI1ActionPerformed(evt);
            }
        });
        jPanel2.add(DI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Total");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 60, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("$100");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 60, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("$300");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 60, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel29.setText("$");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Costo");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 60, -1));

        jTabbedPane1.addTab("Servicio Habitacion ", jPanel2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Costo");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        addL.setBackground(new java.awt.Color(153, 255, 153));
        addL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        addL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLActionPerformed(evt);
            }
        });
        jPanel3.add(addL, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 70, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Gym");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Canchas ");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("$100");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("$300");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Spa");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("$400");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        Salir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aceptar.jpeg.png"))); // NOI18N
        Salir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir1MouseClicked(evt);
            }
        });
        jPanel3.add(Salir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 110, 90));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Aceptar/Salir");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 100, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Total");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 60, -1));

        Gym.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel3.add(Gym, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        Spa.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel3.add(Spa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        Canchas.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel3.add(Canchas, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        txtTotal1.setBackground(new java.awt.Color(255, 255, 102));
        txtTotal1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 51, 51)));
        jPanel3.add(txtTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 150, 60));

        NOTA2.setBackground(new java.awt.Color(255, 204, 153));
        NOTA2.setColumns(20);
        NOTA2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NOTA2.setRows(5);
        NOTA2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jScrollPane4.setViewportView(NOTA2);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 340, 110));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel31.setText("$");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Espacios", jPanel5);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Horas extra");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        extras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        extras.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel4.add(extras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 200, 30));

        costo2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        costo2.setText("0");
        costo2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        costo2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                costo2FocusLost(evt);
            }
        });
        jPanel4.add(costo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 130, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Costo");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        add2.setBackground(new java.awt.Color(153, 255, 153));
        add2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2ActionPerformed(evt);
            }
        });
        jPanel4.add(add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 70, 30));

        horas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        horas.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        horas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                horasStateChanged(evt);
            }
        });
        jPanel4.add(horas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Extra");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("$300");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText(" Lavadora");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        lavadora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lavadora.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        lavadora.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lavadoraStateChanged(evt);
            }
        });
        jPanel4.add(lavadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 80, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("$150");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        Salir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aceptar.jpeg.png"))); // NOI18N
        Salir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir2MouseClicked(evt);
            }
        });
        jPanel4.add(Salir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 110, 90));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Aceptar/Salir");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 100, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Total");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 60, -1));

        txtTotal2.setBackground(new java.awt.Color(255, 255, 102));
        txtTotal2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 51, 51)));
        jPanel4.add(txtTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 150, 60));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel32.setText("$");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 60, -1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Extras", jPanel7);

        CUENTA.setBackground(new java.awt.Color(255, 204, 153));
        CUENTA.setColumns(20);
        CUENTA.setRows(5);
        CUENTA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(0, 0, 0), null, new java.awt.Color(102, 102, 102)));
        jScrollPane3.setViewportView(CUENTA);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("NOTAS", jPanel9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void Limpiar(){
BF.setSelected(false);
NOTA.setText("");
NOTA2.setText("");
}
//public void habilitar(){
//cantidad.setEnabled(true);
//add.setEnabled(true);
//horas.setEnabled(true);
//lavadora.setEnabled(true);
//extras.setEnabled(true);
//costo2.setEnabled(true);
//add2.setEnabled(true);
//}
//public void inhabilitar(){
//cantidad.setEnabled(true);
//add.setEnabled(false);
//horas.setEnabled(false);
//lavadora.setEnabled(false);
//extras.setEnabled(false);
//costo2.setEnabled(false);
//add2.setEnabled(false);
//}
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if ((int)cantidad.getValue()!=0) {
           String N;
            N = "";
            if (DI1.isSelected()==true) {
              int cost= 100 *  (int ) cantidad.getValue();  
              N="Desayuno incluido para :  "+cantidad.getValue()+"  Personas    $"+cost;
              total=cost;
            }
            if(BF.isSelected()==true) {
              int cost= 300 *  (int ) cantidad.getValue();  
              N="Buffete incluido para : "+cantidad.getValue()+"  Personas    $"+cost;
              total=cost;
            }
        NOTA.setText(N);
        txtTotal.setText(String.valueOf(total));    
        cantidad.setValue(0);
        recibo+=NOTA.getText()+"\n";
        CUENTA.setText(recibo); 
        }else{JOptionPane.showMessageDialog(null, "Campos vacios");}
        
    }//GEN-LAST:event_addActionPerformed

    private void addLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLActionPerformed


int totalC=0;
int totalG=0;
int totalS=0;     
String N = "";
        if (Gym.isSelected()) {
          totalG=100;
          N+="GYM ..... $ 100.00\n";
        }
        if (Canchas.isSelected()) {
          totalC=300;
          N+="Canchas ..... $ 300.00\n";
        }
        if (Spa.isSelected()) {
          totalS=400;  
          N+="Spa ..... $ 400.00\n";
        }
        
int total =  totalG+totalC+totalS;
NOTA2.setText(N);
      txtTotal1.setText(String.valueOf(total));
      recibo+=NOTA2.getText()+"\n";
      CUENTA.setText(recibo);
      Gym.setSelected(false);
      Spa.setSelected(false);
      Canchas   .setSelected(false);
    }//GEN-LAST:event_addLActionPerformed

    private void add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ActionPerformed
TAL+=Integer.parseInt(costo2.getText());
recibo+="Extras : "+extras.getText()+"  $"+costo2.getText()+"\n" ;
txtTotal2.setText(String.valueOf(TAL));
CUENTA.setText(recibo);
costo2.setText("0");
extras.setText("");
añadir();
    }//GEN-LAST:event_add2ActionPerformed
private void añadir(){

if ((!(lavadora.getValue().equals(0)&&horas.getValue().equals(0)))) {
            L = (int)lavadora.getValue()*150;
            HEx = (int)horas.getValue()*300;
            TAL+= L+HEx;
            if (!(lavadora.getValue().equals(0))) {
        recibo+="Lavanderia   costo $"+L+"\n"; 
            }
            if (!(horas.getValue().equals(0))) {
        recibo+="Horas Extra   costo $"+HEx+"\n";   
            }
        txtTotal2.setText(String.valueOf(TAL));
        CUENTA.setText(recibo);
        }
        horas.setValue(0);
        lavadora.setValue(0);


}
    private void costo2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_costo2FocusLost
        if (costo2.getText().equals("")) {
            costo2.setText("0");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_costo2FocusLost

    private void horasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_horasStateChanged
        if ((int)horas.getValue()<0) {
           horas.setValue(0);
        }
    }//GEN-LAST:event_horasStateChanged

    private void lavadoraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lavadoraStateChanged
if ((int)lavadora.getValue()<0) {
            lavadora.setValue(0);
        }            // TODO add your handling code here:
    }//GEN-LAST:event_lavadoraStateChanged

    private void BFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFActionPerformed
        if (BF.isSelected()==true) {
            DI1.setSelected(false);
        }
    }//GEN-LAST:event_BFActionPerformed

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
salir();
Limpiar();
ll.clear();
NOTA.setText("");
NOTA2.setText("");   // TODO add your handling code here:
    }//GEN-LAST:event_SalirMouseClicked

    private void DI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DI1ActionPerformed
        if (DI1.isSelected()==true) {
            BF.setSelected(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_DI1ActionPerformed

    private void Salir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir1MouseClicked
salir();
   Limpiar();     
    }//GEN-LAST:event_Salir1MouseClicked

    private void Salir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir2MouseClicked
salir();
Limpiar();  
    }//GEN-LAST:event_Salir2MouseClicked

    private void cantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cantidadStateChanged
int valor = (int) cantidad.getValue();
int numeroP =  (int )JDRESER.NUM.getValue();
        if (valor < 0|| valor>numeroP) {
            cantidad.setValue(0);
        }
        if (valor>numeroP) {
            JOptionPane.showMessageDialog(null,"Excediste el numero de A.C. de la habitacion");
            cantidad.setValue(numeroP);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadStateChanged
public void salir(){
if ((txtTotal.getText().equals(""))) {SH=0;}else{SH+=Integer.parseInt(txtTotal.getText());}
        if ((txtTotal1.getText().equals(""))){E=0;}else{E+=Integer.parseInt(txtTotal1.getText());}
        if ((txtTotal2.getText().equals(""))) {EXTR=0;}else{EXTR+=Integer.parseInt(txtTotal2.getText());} 
        System.out.println(JDRESER.COMPLETO);
        JDRESER.COMPLETO+=SH+E+EXTR;
        System.out.println("-----"+SH);
        System.out.println(E);
        System.out.println(EXTR);
        JDRESER.txtCosto.setText(String.valueOf(JDRESER.COMPLETO));
        System.out.println("Costo"+JDRESER.COMPLETO);
        txtTotal.setText("");
        txtTotal1.setText("");
        txtTotal2.setText("");
        total=0;
        SH=0;
        E=0;
        EXTR=0;
        this.hide();  

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SERVICIOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SERVICIOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SERVICIOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SERVICIOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SERVICIOS dialog = new SERVICIOS(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BF;
    public static javax.swing.JTextArea CUENTA;
    private javax.swing.JRadioButton Canchas;
    private javax.swing.JRadioButton DI1;
    private javax.swing.JRadioButton Gym;
    private javax.swing.JTextArea NOTA;
    private javax.swing.JTextArea NOTA2;
    private javax.swing.JLabel Salir;
    private javax.swing.JLabel Salir1;
    private javax.swing.JLabel Salir2;
    private javax.swing.JRadioButton Spa;
    private javax.swing.JButton add;
    private javax.swing.JButton add2;
    private javax.swing.JButton addL;
    private javax.swing.JSpinner cantidad;
    private javax.swing.JTextField costo2;
    private javax.swing.JTextField extras;
    private javax.swing.JSpinner horas;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner lavadora;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotal1;
    private javax.swing.JTextField txtTotal2;
    // End of variables declaration//GEN-END:variables
}
